# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'BankSimulator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BankSimulator

 pod 'SnapKit', '~> 5.6.0'
 pod 'Charts', '~> 4.1.0'


end
